### ISSUE TITLE
On-by-default feature for symbolicating backtraces

### ISSUE THREAD

**Issue by jrose-signal** [sfackler/rust-log-panics#10]
[signalapp/libsignal](/signalapp/libsignal) is used in our Android and iOS apps, and we currently use log-panics with backtraces enabled. On a user's phone, however, the library binary has been stripped, and so most of `backtrace`'s symbolication support is wasted. (It can often get the top-level entry point, since that's usually a public symbol, but that's not *that* useful for debugging a panic.) In a branch with a custom replacement for log-panics that uses [`Backtrace::new_unresolved`](https://docs.rs/backtrace/0.3.66/backtrace/struct.Backtrace.html#method.new_unresolved) instead of `Backtrace::new`, the final library size was 100KB smaller (about 5% of that binary's total size).

Would you be interested in a feature flag for this mode? Something like

```toml
with-backtrace = ["with-backtrace-unresolved"]
with-backtrace-unresolved = ["backtrace"]
```

Alternately, if you're looking to deprecate or remove the `with-backtrace` feature in favor of the implicit feature provided by `backtrace` being an optional dependency, it could be something like this:

```toml
default-features = ["backtrace-resolve-symbols"]
backtrace-resolve-symbols = [] # has no effect is 'backtrace' is disabled

with-backtrace = ["backtrace"] # deprecated
```

Or should we keep our custom implementation?
